### ISSUE TITLE
What's the difference?

### ISSUE THREAD

**Issue by bash-c** [long-re/Long#1]
It looks cool(especially the logo lol). But what's the main difference from original Ghidra?

> The goal of this project is to allow faster prototyping with more experimental features and for more fluent user experience. Current Ghidra has many "not so intuitional" choices, and that's what we want to change.

It's not so clear that what you've changed.

**Comment by Escapingbug** [comment]
The current status is that we have just decided to start this. But we are on it, there will be some changes very soon. :)

**Comment by bash-c** [comment]
Sounds great.
Keeping eyes on it :)
